// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTL1OJVqpiLzGTySkuTOFcmAcpzay-fQU',
    appId: '1:162247269168:web:7b162d7238d88f0f06c6f5',
    messagingSenderId: '162247269168',
    projectId: 'speedy-anthem-414414',
    authDomain: 'speedy-anthem-414414.firebaseapp.com',
    storageBucket: 'speedy-anthem-414414.appspot.com',
    measurementId: 'G-LCXZGBSLMH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBG19lCKzm5hsRF19RWBz1eH4PUP8hrxsA',
    appId: '1:162247269168:android:f22903e7a1cc69bb06c6f5',
    messagingSenderId: '162247269168',
    projectId: 'speedy-anthem-414414',
    storageBucket: 'speedy-anthem-414414.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDj7yKrYA3cPZjRN8tYk4roQ7MHfhupqjs',
    appId: '1:162247269168:ios:a29a5a4304bb9a4606c6f5',
    messagingSenderId: '162247269168',
    projectId: 'speedy-anthem-414414',
    storageBucket: 'speedy-anthem-414414.appspot.com',
    iosBundleId: 'com.example.firebaseSeries',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDj7yKrYA3cPZjRN8tYk4roQ7MHfhupqjs',
    appId: '1:162247269168:ios:a29a5a4304bb9a4606c6f5',
    messagingSenderId: '162247269168',
    projectId: 'speedy-anthem-414414',
    storageBucket: 'speedy-anthem-414414.appspot.com',
    iosBundleId: 'com.example.firebaseSeries',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTL1OJVqpiLzGTySkuTOFcmAcpzay-fQU',
    appId: '1:162247269168:web:a3b7148f8c251ae406c6f5',
    messagingSenderId: '162247269168',
    projectId: 'speedy-anthem-414414',
    authDomain: 'speedy-anthem-414414.firebaseapp.com',
    storageBucket: 'speedy-anthem-414414.appspot.com',
    measurementId: 'G-89MEXF1L2E',
  );
}
